import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeTgChatIdToBigInt1743152219652 implements MigrationInterface {
    name = 'ChangeTgChatIdToBigInt1743152219652'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP CONSTRAINT "FK_c4635a397cb663e6bf30c604c5a"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP CONSTRAINT "FK_743353079291feb50cc978759c6"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP CONSTRAINT "FK_a195e01627b8723c739799b1bf0"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP CONSTRAINT "FK_13693845a646bf8c7844eb6ddfb"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP CONSTRAINT "FK_ac4033f578326226212d4ef8f17"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP CONSTRAINT "FK_a17affe0ac9517e25fd2c6ac963"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP CONSTRAINT "HOSPITALS_PATIENTS_UQ"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP CONSTRAINT "HOSPITALS_DOCTORS_UQ"`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "inviteEndAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "language"`);
        await queryRunner.query(`DROP TYPE "public"."doctors_language_enum"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "patientId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "hospitalId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "hospitalId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "medicalCardNumber"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "medicalCardNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ALTER COLUMN "firstName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ALTER COLUMN "lastName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "updatedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "doctorId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "hospitalId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "hospitalId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "updatedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "patientsLimit" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "UQ_64e2031265399f5690b0beba6a5" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "fcmToken"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "fcmToken" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "isFirstSignUp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "isFirstSignUp" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "lastAuthProvider"`);
        await queryRunner.query(`DROP TYPE "public"."patients_lastauthprovider_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "lastAuthProvider" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "language"`);
        await queryRunner.query(`DROP TYPE "public"."patients_language_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "language" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "notificationsSettings"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "notificationsSettings" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."patients_role_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "role" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "tgChatId"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "tgChatId" bigint`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP CONSTRAINT "DOCTORS_PATIENTS_UQ"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "patientId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "doctorId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "updatedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "DOCTOR_EMAIL_UQ"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "UQ_62069f52ebba471c91de5d59d61" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "notificationsSettings" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."doctors_role_enum"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "role" character varying NOT NULL DEFAULT 'doctor'`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "tgChatId"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "tgChatId" bigint`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "deletedAt" TIMESTAMP`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "tgChatId"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "tgChatId" integer`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."doctors_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "role" "public"."doctors_role_enum" NOT NULL DEFAULT 'doctor'`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "notificationsSettings" SET DEFAULT '{"contactMeRequest": true, "criticalIndicators": true, "uploadAnalyzesByPatients": true}'`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "password" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "UQ_62069f52ebba471c91de5d59d61"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "DOCTOR_EMAIL_UQ" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "doctorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD "patientId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD CONSTRAINT "DOCTORS_PATIENTS_UQ" UNIQUE ("patientId")`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "tgChatId"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "tgChatId" integer`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."patients_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "role" "public"."patients_role_enum" NOT NULL DEFAULT 'patient'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "notificationsSettings"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "notificationsSettings" jsonb NOT NULL DEFAULT '{"newSurvey": true}'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "language"`);
        await queryRunner.query(`CREATE TYPE "public"."patients_language_enum" AS ENUM('ru', 'en', 'kz', 'de')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "language" "public"."patients_language_enum" NOT NULL DEFAULT 'ru'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "lastAuthProvider"`);
        await queryRunner.query(`CREATE TYPE "public"."patients_lastauthprovider_enum" AS ENUM('email')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "lastAuthProvider" "public"."patients_lastauthprovider_enum" NOT NULL DEFAULT 'email'`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "isFirstSignUp" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "isFirstSignUp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "fcmToken"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "fcmToken" text`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "password" text`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "UQ_64e2031265399f5690b0beba6a5"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "patientsLimit" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "hospitalId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "hospitalId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD "doctorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ALTER COLUMN "lastName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ALTER COLUMN "firstName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "medicalCardNumber"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "medicalCardNumber" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "hospitalId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "hospitalId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD "patientId" uuid NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."doctors_language_enum" AS ENUM('ru', 'en', 'kz', 'de')`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "language" "public"."doctors_language_enum" NOT NULL DEFAULT 'ru'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "inviteEndAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD CONSTRAINT "HOSPITALS_DOCTORS_UQ" UNIQUE ("doctorId", "hospitalId")`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD CONSTRAINT "HOSPITALS_PATIENTS_UQ" UNIQUE ("patientId", "hospitalId")`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD CONSTRAINT "FK_a17affe0ac9517e25fd2c6ac963" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD CONSTRAINT "FK_ac4033f578326226212d4ef8f17" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD CONSTRAINT "FK_13693845a646bf8c7844eb6ddfb" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD CONSTRAINT "FK_a195e01627b8723c739799b1bf0" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD CONSTRAINT "FK_743353079291feb50cc978759c6" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD CONSTRAINT "FK_c4635a397cb663e6bf30c604c5a" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
